Don't let zubbi-scraper crash on empty repositories
Currently, zubbi-scraper crashes when a repository is empty as we except
the root directoy to exist [1].

Theoretically, we already have tests for that in place, but the mocked
repository class also ensures that the repository root always exists.

To fix this, we catch the CheckOutError which is returned by our GitHub
connection class and adapt our test classes accordingly to cover the
case of a "missing root directory" in a repository.

[1]:
    2022-11-21T15:55:25Z DEBUG [zubbi.scraper.repos.github] Listing contents of '/' directory
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/repos/github.py", line 75, in directory_contents
        remote_directory = self._repo.directory_contents(
      File "/usr/local/lib/python3.8/dist-packages/github3/repos/repo.py", line 1488, in directory_contents
        json = self._json(self._get(url, params={"ref": ref}), 200) or []
      File "/usr/local/lib/python3.8/dist-packages/github3/models.py", line 161, in _json
        raise exceptions.error_for(response)
    github3.exceptions.NotFoundError: 404 This repository is empty.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/zubbi-scraper", line 8, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/main.py", line 249, in scrape
        scrape_outdated(
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/main.py", line 333, in scrape_outdated
        scrape_repo_list(
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/main.py", line 434, in scrape_repo_list
        return _scrape_repo_map(
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/main.py", line 531, in _scrape_repo_map
        scrape_repo(repo, tenants, reusable_repos, scrape_time)
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/main.py", line 559, in scrape_repo
        job_files, role_files = Scraper(repo).scrape()
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/scraper.py", line 49, in scrape
        job_files = self.scrape_job_files()
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/scraper.py", line 56, in scrape_job_files
        job_files = self.iterate_directory(
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/scraper.py", line 81, in iterate_directory
        remote_files = self.repo.directory_contents(path)
      File "/usr/local/lib/python3.8/dist-packages/zubbi/scraper/repos/github.py", line 80, in directory_contents
        raise CheckoutError(directory_path, "Directory not found.")
    zubbi.scraper.exceptions.CheckoutError: Failed to check out '/': Directory not found.