Fix scraper startup on unknown connection
Currently, initializing the tenant parser fails when an unknown
connection is used to specify the TENANT_SOURCES_REPO in the zubbi
settings file:

    Traceback:
      File "/workspace/zubbi/zubbi/scraper/main.py", line 227, in scrape
        tenant_parser = _initialize_tenant_parser(
      File "/workspace/zubbi/zubbi/scraper/main.py", line 89, in _initialize_tenant_parser
        provider = con.provider
    AttributeError: 'NoneType' object has no attribute 'provider'

This can be fixed by moving a NoneType check a few lines further up.
Additionally, make the error message a little bit clearer.