Validate that the description is rendered correctly in the details view
I saw a problem in my local dev setup where the description in zubbi-web
wasn't rendered at all, because elasticsearch_dsl wasn't able to look up
the `description_rendered` property (which should exist). However I did
not manage to reproduce this problem anywhere else.

To ensure that this is only a local hickup and no general problem, let's
add a test to validate that the description is rendered properly.

Traceback (most recent call last):
  ...
  File "/tmp/zubbi/zubbi/scraper/main.py", line 239, in scrape
    scrape_full(connections, reusable_repos, tenant_parser, repos=repo)
  File "/tmp/zubbi/zubbi/scraper/main.py", line 362, in scrape_full
    scrape_repo_list(repos, connections, reusable_repos, tenant_parser)
  File "/tmp/zubbi/zubbi/scraper/main.py", line 434, in scrape_repo_list
    return _scrape_repo_map(
  File "/tmp/zubbi/zubbi/scraper/main.py", line 531, in _scrape_repo_map
    scrape_repo(repo, tenants, reusable_repos, scrape_time)
  File "/tmp/zubbi/zubbi/scraper/main.py", line 564, in scrape_repo
    ).parse()
  File "/tmp/zubbi/zubbi/scraper/repo_parser.py", line 45, in parse
    repo_jobs = self.parse_job_files()
  File "/tmp/zubbi/zubbi/scraper/repo_parser.py", line 54, in parse_job_files
    jobs = self.parse_job_definitions(rel_job_file_path, job_info)
  File "/tmp/zubbi/zubbi/scraper/repo_parser.py", line 109, in parse_job_definitions
    LOGGER.warning("description rendered: %s", job.description_rendered)
  File "tmp/virtualenvs/zubbi-QuWGSy69/lib/python3.10/site-packages/elasticsearch_dsl/utils.py", line 489, in __getattr__
    return super(ObjectBase, self).__getattr__(name)
  File "tmp/virtualenvs/zubbi-QuWGSy69/lib/python3.10/site-packages/elasticsearch_dsl/utils.py", line 161, in __getattr__
    raise AttributeError(
AttributeError: 'ZuulJob' object has no attribute 'description_rendered'